[project]
name = "ride"
id = "ru.marslab.ide.ride"
type = "intellij"

[build]
gradle_task = "buildPlugin"
output_dir = "build/distributions"

[repository]
url = "http://158.160.107.227/updatePlugins.xml"
ssh_host = "your-server.com"
ssh_user = "deploy-user"
deploy_path = "/var/www/plugins/archives/"
xml_path = "/var/www/plugins/updatePlugins.xml"

[llm]
provider = "yandexgpt"
temperature = 0.3
max_tokens = 2000

[yandexgpt]
api_key = "${DEPLOY_PLUGIN_YANDEX_API_KEY}"
folder_id = "${DEPLOY_PLUGIN_YANDEX_FOLDER_ID}"
model = "yandexgpt"

[llm_agents]
changelog_agent = { model = "yandexgpt", temperature = 0.3 }
version_agent = { model = "yandexgpt-lite", temperature = 0.1 }
release_agent = { model = "yandexgpt", temperature = 0.4 }

[git]
main_branch = "main"
tag_prefix = "v"
